image: crazymax/docker

variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_SLUG

services:
  - docker:dind

workflow:
  rules:
    - if: '$CI_COMMIT_REF_SLUG == "main"'
      variables:
        IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
    - when: always


prebuild:
  stage: .pre
  script:
    - export

build:
  stage: build
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker buildx create --use
    - docker buildx build --push --platform linux/arm64/v8,linux/amd64 --tag $IMAGE_TAG .